title: Анастасия Грибанова
logo: "/images/logo.png?raw=true" 
description: > # your text below (remove <br> elements if you don't need line breaks)
  ML-инженер 
  <br><br>
  *Образование:* 
  <br><br>
  Казанский Федеральный Университет Институт Информационных технологий и интеллектуальных систем
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: 

colors:
  crimson: '#900C3F'
