title: <big>Анастасия Грибанова</big>
logo: "/images/logo.png?raw=true" 
description: > # your text below (remove <br> elements if you don't need line breaks)
  <big><b>ML-инженер</b> </big>
  <br><br>
   <b>Образование: </b>
  <br>
  Казанский Федеральный Университет Институт Информационных технологий и интеллектуальных систем
  
theme: jekyll-theme-minimal
plugins:
- jekyll-remote-theme
google_analytics: 

colors:
  crimson: '#900C3F'
